begin;
select plan(16);
select tests.create_supabase_user('month_referrer', 'month-referrer@example.com');
select tests.create_supabase_user('month_legacy', 'month-legacy@example.com');
select tests.create_supabase_user('month_friend1', 'month-friend1@example.com');
select tests.create_supabase_user('month_friend2', 'month-friend2@example.com');
select tests.create_supabase_user('month_friend3', 'month-friend3@example.com');
update auth.users set email_confirmed_at=now() where id in (
  tests.get_supabase_uid('month_friend1'),tests.get_supabase_uid('month_friend2'),tests.get_supabase_uid('month_friend3'));
update public.profiles set stripe_customer_id='cus_month_ref' where id=tests.get_supabase_uid('month_referrer');
insert into stripe.customers(id) values ('cus_month_ref');
insert into stripe.products(id,name) values ('prod_month_ref','Pro');
insert into stripe.prices(id,product,unit_amount,currency) values ('price_month_ref','prod_month_ref',1400,'usd');
insert into stripe.subscriptions(id,customer,status,created) values ('sub_month_ref','cus_month_ref','active',extract(epoch from now())::integer);
insert into stripe.subscription_items(id,subscription,price,quantity) values ('si_month_ref','sub_month_ref','price_month_ref',1);
insert into private.referral_invites(referrer_user_id,slot,code,referred_user_id,claimed_at,reward_amount_cents)
values (tests.get_supabase_uid('month_referrer'),1,'aaaaaaaaaaaaaaaaaaaaaaaa',tests.get_supabase_uid('month_legacy'),now(),1500);
update private.referral_program set price_ids=array['price_month_ref'],enabled=true;
select tests.authenticate_as('month_referrer');
create temporary table month_link as select public.get_referral_summary()->>'code' as code;
select is((public.get_referral_summary()->>'remaining')::integer,2,'Legacy acceptance consumes one of three places');
select is(public.get_referral_summary()->'invites'->0->>'policy','legacy_payment','Accepted legacy offer stays payment-triggered');
select tests.clear_authentication(); reset role;
grant select on month_link to authenticated;
select tests.authenticate_as('month_friend1');
select ok(public.claim_referral((select code from month_link)),'First new account can accept personal link');
select ok(public.claim_referral((select code from month_link)),'Repeated acceptance is idempotent');
select is(public.get_referral_trial_days(),30,'Referred account gets a 30-day trial');
select tests.clear_authentication(); reset role;
select tests.authenticate_as('month_friend2');
select ok(public.claim_referral((select code from month_link)),'Same link accepts another account');
select tests.clear_authentication(); reset role;
select tests.authenticate_as('month_friend3');
select ok(not public.claim_referral((select code from month_link)),'Fourth acceptance including legacy is blocked');
select tests.clear_authentication(); reset role;
select is((select count(*) from public.prepare_referral_reward(tests.get_supabase_uid('month_friend1'),'in_newmonth')),0::bigint,'New-policy referrals cannot also earn invoice credit');
select is((select reward_amount_cents from public.prepare_referral_reward(tests.get_supabase_uid('month_legacy'),'in_oldmonth')),1500,'Legacy amount is preserved');
select tests.authenticate_as('month_referrer');
select is((public.get_referral_summary()->>'months_earned')::integer,0,'Acceptance alone is not a completed reward');
select ok(not public.referral_link_available((select code from month_link)), 'Exhausted links are rejected before signup');
select ok(not has_table_privilege('authenticated','private.referral_events','SELECT'), 'Audit trail is not exposed to ordinary users');
select tests.clear_authentication(); reset role;
update stripe.subscriptions set status='trialing', trial_end=to_jsonb(extract(epoch from now()+interval '3 days')::bigint), metadata='{}'::jsonb where id='sub_month_ref';
select tests.authenticate_as('month_referrer');
select is((public.get_referral_summary()->>'eligible')::boolean,true,'Active cardless trial referrers are eligible');
select tests.clear_authentication(); reset role;
update stripe.subscriptions set trial_end=to_jsonb(extract(epoch from now()-interval '1 day')::bigint) where id='sub_month_ref';
select ok(not private.can_refer_for_month(tests.get_supabase_uid('month_referrer')),'Expired trials cannot invite');
update stripe.subscriptions set status='paused', trial_end=to_jsonb(extract(epoch from now()+interval '3 days')::bigint) where id='sub_month_ref';
select ok(not private.can_refer_for_month(tests.get_supabase_uid('month_referrer')),'Paused trials cannot invite');
update stripe.subscriptions set status='trialing' where id='sub_month_ref';
update stripe.subscription_items set price='price_other' where subscription='sub_month_ref';
select ok(not private.can_refer_for_month(tests.get_supabase_uid('month_referrer')),'Trials on unconfigured prices cannot invite');
select * from finish();
rollback;
