packages:
  - apps/*
  - packages/*
  - plugins/*
  - examples/plugins/*
  - e2e/*

onlyBuiltDependencies:
  - supabase
  - "@infisical/cli"
  - esbuild
  - "@swc/core"
  - "@parcel/watcher"
  - sharp
  - dprint
  - protobufjs
