// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async isAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("plugin:meet-client|is_available");
},
async joinMeeting(meetingUrl: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:meet-client|join_meeting", { meetingUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async leaveMeeting() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:meet-client|leave_meeting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStatus() : Promise<MeetMeetingStatus> {
    return await TAURI_INVOKE("plugin:meet-client|get_status");
},
async setSelectors(selectors: MeetSelectors) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:meet-client|set_selectors", { selectors }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Invoked by the observer script running inside the Meet webview.
 */
async reportObservation(observation: MeetObservation) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:meet-client|report_observation", { observation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
meetClientEvent: MeetClientEvent
}>({
meetClientEvent: "plugin:meet-client:meet-client-event"
})

/** user-defined constants **/



/** user-defined types **/

export type MeetActiveSpeakers = { at_ms: number; participant_ids: string[] }
export type MeetClientEvent = { type: "state_changed"; data: { session_id: string; state: MeetClientState; reason: string | null } } | { type: "participant_upserted"; data: { session_id: string; participant: MeetParticipant } } | { type: "participant_left"; data: { session_id: string; participant_id: string } } | { type: "active_speakers"; data: { session_id: string; speakers: MeetActiveSpeakers } } | { type: "error"; data: { session_id: string; message: string } }
export type MeetClientState = "idle" | "launching" | "waiting_for_admission" | "capturing" | "stopping" | "ended"
export type MeetMeetingStatus = { session_id: string | null; state: MeetClientState; participants: MeetParticipant[] }
/**
 * One snapshot of the Meet DOM, posted by the injected observer.
 */
export type MeetObservation = { inMeeting: boolean; ended: boolean; participants: ObservedParticipant[] }
export type MeetParticipant = { id: string; display_name: string | null; email: string | null }
/**
 * DOM selectors the injected observer uses to read the Meet web client. Google
 * ships obfuscated class names that rotate, so these are overridable at runtime
 * (`set_selectors`) instead of baked into the binary.
 */
export type MeetSelectors = { 
/**
 * Elements that represent one participant each; must carry `participantIdAttribute`.
 */
tile: string; participantIdAttribute: string; 
/**
 * Elements inside a tile whose text (or `nameAttribute`) is the display name.
 */
name: string; nameAttribute: string; 
/**
 * Speaking indicator inside a tile; considered active unless it has `silentClass`.
 */
speakingIndicator: string; silentClass: string; 
/**
 * Present only while in the meeting (not on the lobby / "Ready to join" page).
 */
inMeeting: string; 
/**
 * Present once the meeting has ended or the user has left.
 */
ended: string; pollMs: number }
export type ObservedParticipant = { id: string; displayName: string | null; speaking: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
