// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async isAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("plugin:zoom-client|is_available");
},
async joinMeeting(meetingUrl: string, displayName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:zoom-client|join_meeting", { meetingUrl, displayName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async leaveMeeting() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:zoom-client|leave_meeting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStatus() : Promise<ZoomMeetingStatus> {
    return await TAURI_INVOKE("plugin:zoom-client|get_status");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
zoomClientEvent: ZoomClientEvent
}>({
zoomClientEvent: "plugin:zoom-client:zoom-client-event"
})

/** user-defined constants **/



/** user-defined types **/

export type ZoomActiveSpeakers = { at_ms: number; participant_ids: string[] }
export type ZoomClientEvent = { type: "state_changed"; data: { session_id: string; state: ZoomClientState; reason: string | null } } | { type: "participant_upserted"; data: { session_id: string; participant: ZoomParticipant } } | { type: "participant_left"; data: { session_id: string; participant_id: string } } | { type: "active_speakers"; data: { session_id: string; speakers: ZoomActiveSpeakers } } | { type: "error"; data: { session_id: string; message: string } }
export type ZoomClientState = "idle" | "launching" | "waiting_for_admission" | "joined" | "capturing" | "stopping" | "ended"
export type ZoomMeetingStatus = { session_id: string | null; state: ZoomClientState; participants: ZoomParticipant[] }
export type ZoomParticipant = { id: string; display_name: string | null; email: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
