[package]
name = "tauri-plugin-shortcut"
version = "0.1.0"
edition = "2024"
exclude = ["/js", "/node_modules"]
links = "tauri-plugin-shortcut"

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }

[dev-dependencies]
specta-typescript = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }
tauri-plugin-global-shortcut = "2.3.2"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }

tauri = { workspace = true, features = ["test"] }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }

[target.'cfg(target_os = "macos")'.dependencies]
anlg-shortcut-macos = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "0.13.13", default-features = false, features = ["tokio", "global_shortcuts"] }
futures-util = { workspace = true }
