name: web_ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/web/**
      - packages/api-client/**
      - packages/changelog/**
      - packages/pricing/**
      - packages/supabase/**
      - packages/tiptap/**
      - packages/ui/**
      - packages/utils/**
      - plugins/auth/**
      - plugins/deeplink2/**
      - package.json
      - pnpm-workspace.yaml
      - turbo.json
      - .github/workflows/web_ci.yaml
      - .github/actions/pnpm_install/**
  pull_request:
    paths:
      - apps/web/**
      - packages/api-client/**
      - packages/changelog/**
      - packages/pricing/**
      - packages/supabase/**
      - packages/tiptap/**
      - packages/ui/**
      - packages/utils/**
      - plugins/auth/**
      - plugins/deeplink2/**
      - package.json
      - pnpm-workspace.yaml
      - turbo.json
      - .github/workflows/web_ci.yaml
      - .github/actions/pnpm_install/**
jobs:
  ci:
    runs-on: depot-ubuntu-24.04-4
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm_install
      - run: pnpm -F ui build
      - run: pnpm -F web typecheck
