name: web_ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/web/**
      - packages/**
  pull_request:
    paths:
      - apps/web/**
      - packages/**
jobs:
  ci:
    runs-on: depot-ubuntu-24.04-4
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm_install
      - run: pnpm -F ui build
      - run: pnpm -F web typecheck
